routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { 
    return view('welcome');
});

Auth::routes();

//  Route::controller(MemberController::class)->group(function(){
//      Route::get('/register', 'register')->name('register');
//  });



// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/admin', 'UserAccountController@admin')->name('admin')->middleware('super');
// Route::get('/user', 'UserAccountController@user')->name('user')->middleware('member');
// Route::get('/member', 'UserAccountController@memberadmin')->name('member-mgr')->middleware('memberadmin');

// UserAccountController ROUTES



Route::get('pradmin/musuem', 'MuseumRecordController@index');
Route::get('pradmin/musuem/create','MuseumRecordController@create');
Route::get('pradmin/musuem/{id}/edit','MuseumRecordController@edit')->name('editMuseumPost');


Route::get('/pradmin/posts', 'EventController@index')->name('events');
Route::get('pradmin/posts/create','EventController@create');
Route::get('pradmin/posts/{id}/edit','EventController@edit')->name('editPost');

Route::resource('musuem','MuseumRecordController');
Route::resource('posts','EventController');



Route::get('/events', 'PagesController@event');
Route::get('/museum', 'PagesController@museum');



Route::controller(PagesController::class)->group(function(){
    Route::get('/','index');
    Route::get('/about','about');
    Route::get('/events/upcomingevent','events');
    Route::get('/events/pastevent','events');
    Route::get('/museum','museum');
    Route::get('/contact','contactus');
});

Route::resource('member/manage-members', MemberController::class);
Route::get('/member','MemberController@home')->name('member-mgr')->middleware('memberadmin');
Route::get('/register','MemberController@register')->name('register');


// Route::post('/login', 'UserAccountController@login');


//  AdminController
Route::resource('admin/managemgrs', AdminController::class);
Route::get('/admin','AdminController@home')->name('admin')->middleware('super');


Route::controller(UserAccountController::class)->group(function(){
    Route::get('/pradmin','pradmin')->name('pradmin')->middleware('pradmin');
    Route::get('/user','user')->name('user')->middleware('member');
    Route::get('/financeAdmin','financemgr')->name('financemgr')->middleware('financeadmin');
    Route::get('/educAdmin','educmgr')->name('educmgr')->middleware('educadmin');
    Route::post('/login', 'login');
});

//Church Profile Routing

Route::resource('/pradmin/church_profile', ChurchProfileController::class);

resources/views/event_museum_record_admin/posts/edit.blade.php
@extends('pradmin.dashboard')
@section('content')
<div class="container">
<h1>edit post post</h1>

{!! Form::open(['route'=>['posts.update',$posts->id],'method'=>'POST','enctype'=>'multipart/form-data'])!!}
<div class="form-group">
    {{Form::label('title','Title')}}
    {{Form::text('title',$posts->title,['class'=>'form-control','placeholder'=>'Title'])}}
    </div>

    <div class="form-group mb-3">     
        {{Form::label('title','Description:')}}
         {{Form::textarea('description',$posts->description,['class'=>'form-control','placeholder'=>'type your description here..'])}}

</div>
<div class="form-group mb-3">     
        {{Form::file('post_emage')}}
</div> 
{{Form::hidden('_method','PUT')}}
{{Form::submit('Submit',['class'=>'btn btn-primary'])}}
{!!Form::close()!!}

</div>
@endsection

resources/views/event_museum_record_admin/posts/event.blade.php
@extends('pradmin.dashboard')
@section('dashboardtitle')
    Dashboard-Manage Events
@endsection
@section('content')
<div class="container">

<a href="posts/create" class="btn btn-primary m-4">Create post</a>
@if(count($posts)>0)
<div class="flex justify-center">
    <div class="w-8/12 bg-white p-6 rounded-lg">
        
<div class="card">
    
    <ul class="list-group list-group-flush">
        <a href="" class="btn btn-primary"></a>
    @foreach($posts as $post)
     
    <div class="row mb-4">
        <div class="col-md-4">
            <img style="width:300px;"src="/storage/post_images/{{$post->post_image}}" >
            
        </div>
    
        <div class="col-md-8">
            <h1>{{$post->title}}</h1>
            <p>{{$post->description}}</p> 
            
        <p>
         <div style="display: flex;">
            <a href="{{route('editPost',['id'=>$post->id])}}" class="btn btn-primary">Update</a>
            {!!Form::open(['route' => ['posts.destroy', $post->id], 'method' => 'POST', 'class' => 'pull-right'])!!}
            {{Form::hidden('_method', 'DELETE')}}
            {{Form::submit('Delete', ['class' => 'btn btn-danger'])}}
            {!!Form::close()!!}
        </div>
       </p>  
          
    <p><a href="#" class="link-item " style="text-decoration: none;">Posted: {{$post->created_at->diffForHumans()}}</a></p>
    
         
           
        </div>
 </div>
       <hr>
    
    @endforeach
   
    </ul>
    </div>
    </div>
</div>
    
</div>
@endif

@endsection

resources/views/event_museum_record_admin/posts/post.blade.php
@extends('pradmin.dashboard')
@section('content')
<div class="container">
<h1>create post</h1>
<div class="flex justify-center">
    <div class="w-6/12 bg-white p-6 rounded-lg">
 
<form action="{{route('posts.store')}}" method="POST" enctype="multipart/form-data">
     @csrf
     
     <div class="form-outline mb-4">
     
    <label class="form-label" for="title" >Title</label>
    <input type="text" name="title" class="form-control" />
  </div>
 <!-- Message input -->
  <div class="form-outline mb-4"> 
     <label class="form-label" for="description">Description</label>
    <textarea class="form-control" name="description"  rows="4"></textarea>

  </div>

   <div class="form-outline mb-4">
    <input type="file" id="form3example3" name="post_image"class="form-control" />
    
  </div>


  <!-- Submit button -->
  <button type="submit" class="btn btn-primary btn-block mb-4"> Post </button>
</form>
    </div>
</div>
</div>
@endsection

resources/views/event_museum_record_admin/posts/show.blade.php
@extends('pradmin.dashboard')
@section('content')
<a href="/posts" class="btn btn-primary">Go back</a>
<h1>{{$posts->title}}</h1>
<div class="row">
    <div class="col-md-12">
    <img style="width:300px;"src="/storage/post_images/{{$posts->post_image}}" >
    </div>

</div>
<p>{{$posts->description}}</p>
<small>created on{{$posts->created_at}}</small>
<hr>
<div style="display: flex;">
 <a href="/posts/{{$posts->id}}/edit" class="btn btn-primary">Update</a>
 {!!Form::open(['route' => ['posts.destroy', $posts->id], 'method' => 'POST', 'class' => 'pull-right'])!!}
    {{Form::hidden('_method', 'DELETE')}}
    {{Form::submit('Delete', ['class' => 'btn btn-danger'])}}
{!!Form::close()!!}
</div>
 @endsection