routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { 
    return view('welcome');
});

Auth::routes();

//  Route::controller(MemberController::class)->group(function(){
//      Route::get('/register', 'register')->name('register');
//  });



// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/admin', 'UserAccountController@admin')->name('admin')->middleware('super');
// Route::get('/user', 'UserAccountController@user')->name('user')->middleware('member');
// Route::get('/member', 'UserAccountController@memberadmin')->name('member-mgr')->middleware('memberadmin');

// UserAccountController ROUTES



Route::get('pradmin/musuem', 'MuseumRecordController@index');
Route::get('pradmin/musuem/create','MuseumRecordController@create');
Route::get('pradmin/musuem/{id}/edit','MuseumRecordController@edit')->name('editMuseumPost');


Route::get('/pradmin/posts', 'EventController@index')->name('events');
Route::get('pradmin/posts/create','EventController@create');
Route::get('pradmin/posts/{id}/edit','EventController@edit')->name('editPost');

Route::resource('musuem','MuseumRecordController');
Route::resource('posts','EventController');



Route::get('/events', 'PagesController@event');
Route::get('/museum', 'PagesController@museum');



Route::controller(PagesController::class)->group(function(){
    Route::get('/','index');
    Route::get('/about','about');
    Route::get('/events/upcomingevent','events');
    Route::get('/events/pastevent','events');
    Route::get('/museum','museum');
    Route::get('/contact','contactus');
});

Route::resource('member/manage-members', MemberController::class);
Route::get('/member','MemberController@home')->name('member-mgr')->middleware('memberadmin');
Route::get('/register','MemberController@register')->name('register');


// Route::post('/login', 'UserAccountController@login');


//  AdminController
Route::resource('admin/managemgrs', AdminController::class);
Route::get('/admin','AdminController@home')->name('admin')->middleware('super');


Route::controller(UserAccountController::class)->group(function(){
    Route::get('/pradmin','pradmin')->name('pradmin')->middleware('pradmin');
    Route::get('/user','user')->name('user')->middleware('member');
    Route::get('/financeAdmin','financemgr')->name('financemgr')->middleware('financeadmin');
    Route::get('/educAdmin','educmgr')->name('educmgr')->middleware('educadmin');
    Route::post('/login', 'login');
});

//Church Profile Routing

Route::resource('/pradmin/church_profile', ChurchProfileController::class);

app/Models/ChurchProfile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ChurchProfile extends Model
{
    use HasFactory;
    protected $guarded=[];
}

app/Http/Controllers/ChurchProfileController.php
<?php

namespace App\Http\Controllers;
use App\Models\ChurchProfile;
use Illuminate\Http\Request;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Support\Facades\Auth;


class ChurchProfileController extends Controller
{
  
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts=ChurchProfile::all();
        return view('pradmin.church_profile.churchProfile')->with('posts',$posts);
    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
return view('pradmin.church_profile.createProfile');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request,[
            'churchName'=>'required',
            	'photo'=>'required',
                'address'=>'required',
                	'email'=>'required',
                    	'phone'=>'required',
        ]);


        

         //handle the file upload
        if($request->hasFile('photo')){
            //get file name extension

            $fienamewithExt=$request->file('photo')->getClientOriginalName();
                //get file name
            $filename=pathinfo($fienamewithExt,PATHINFO_FILENAME);
                //get file extension
            $extension=$request->file('photo')->getClientOriginalExtension();
                //file name to store
            $fileNameToStore=$filename .'_'.time().'.'.$extension;

            $path=$request->file('photo')->storeAs('public/churchP_images',$fileNameToStore);


        }else{
            $fileNameToStore='noimage.jpg';
        }

        $posts=new ChurchProfile;
        $posts->churchName=$request->input('churchName');
        $posts->address=$request->input('address');
        $posts->email=$request->input('email');
        $posts->phone=$request->input('phone');
        $posts->admin_id=Auth::user()->admin_id;
        $posts->photo=$fileNameToStore;
        $posts->save();
        return redirect('pradmin/church_profile')->with('success', 'Church profile created');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $posts=ChurchProfile::find($id);
        return view('pradmin.church_profile.editprofile')->with('posts',$posts);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'churchName'=>'required',
            	'photo'=>'required',
                'address'=>'required',
                	'email'=>'required',
                    	'phone'=>'required',
        ]);
       
        //handle the file upload
        if($request->hasFile('photo')){
            //get file name extension

            $fienamewithExt=$request->file('photo')->getClientOriginalName();
                //get file name
            $filename=pathinfo($fienamewithExt,PATHINFO_FILENAME);
                //get file extension
            $extension=$request->file('photo')->getClientOriginalExtension();
                //file name to store
            $fileNameToStore=$filename .'_'.time().'.'.$extension;

            $path=$request->file('photo')->storeAs('public/churchP_images',$fileNameToStore);


        }else{
            $fileNameToStore='noimage.jpg';
        }

        $posts= ChurchProfile::find($id);
        $posts->churchName=$request->input('churchName');
        $posts->address=$request->input('address');
        $posts->email=$request->input('email');
        $posts->phone=$request->input('phone');
        $posts->photo=$fileNameToStore;
        $posts->save();
        return redirect('/churchprofile')->with('success', 'cuhrch profile created');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        

    }
}

resources/views/pradmin/church_profile/churchProfile.blade.php
@extends('pradmin.dashboard')
@section('content')
@if (!count($posts)>0)
    <a href="{{action('ChurchProfileController@create')}}" class="btn btn-primary mb-4">Create Profile</a>
@endif

@foreach ($posts as $post )
    

<h1>{{$post->churchName}}</h1>
<div class="row">
   
    <img style="width:100%;"src="/storage/churchP_images/{{$post->photo}}" >
    
<h1>Address: {{$post->address}}</h1>
<h1>Email: {{$post->email}}</h1>
<h1>Phone number:+251{{$post->phone}}</h1>
</div>
<p>{{$post->description}}</p>
<small>created on{{$post->created_at}}</small>
<hr>
@if(!Auth::guest())
<div style="display: flex;">
    <a href="church_profile/{{$post->id}}/edit" class="btn btn-primary">Update</a>
 </div>
    @endif

@endforeach
 @endsection

resources/views/pradmin/church_profile/createProfile.blade.php
@extends('pradmin.dashboard')
@section('content')
<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
       
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Create church profile</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
			<form action="{{route('church_profile.store')}}" method="POST" enctype="multipart/form-data">
      @csrf
            <div class="card-body">

              <div class="form-group">
                  <label class="form-label" for="churchName" >Church Name</label>
                  <input type="text" name="churchName" class="form-control" />
              </div>

               <div class="form-group">
                <label class="form-label" for="address" >address</label>
                <input type="text" name="address" class="form-control" />
              </div>

             <div class="form-group">
                <label class="form-label" for="email" >email</label>
                <input type="email" name="email" class="form-control" />
              </div>

                <div class="form-group mb-4">
                  <label class="form-label" for="phone" >phone</label>
                  <input type="number" name="phone" class="form-control" />
              </div>
               <div class="form-group">
                   <input type="file" name="photo" class="form-control" />
              </div>

              <div class="form-group">
                 <input type="submit" value="Create" class="btn btn-success float-right">
              </div>
          
             
            </div>
			</form>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        
      </div>
     
       
    </section>
    <!-- /.content -->
  </div>

</div> 
 @endsection

resources/views/pradmin/church_profile/editprofile.blade.php
@extends('layouts.app')
@section('content')
<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
       
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Create church profile</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
			<form action="{{route('church_profile.update',[$posts->id])}}" method="POST" enctype="multipart/form-data">
      @csrf
      @method('PUT')
            <div class="card-body">

              <div class="form-group">
                  <label class="form-label" for="churchName" >Church Name</label>
                  <input type="text" name="churchName" value="{{$posts->churchName}}" class="form-control" />
              </div>

               <div class="form-group">
                  <label class="form-label" for="address" >address</label>
                  <input type="text" name="address" value="{{$posts->address}}" class="form-control" />          
              </div>

             <div class="form-group">
                  <label class="form-label" for="email" >email</label>
                  <input type="email" name="email"value="{{$posts->email}}" class="form-control" />
              </div>

                <div class="form-group mb-4">
                  <label class="form-label" for="phone" >phone</label>
                  <input type="number" name="phone"value="{{$posts->phone}}" class="form-control" />
              </div>
               <div class="form-group">
                   <input type="file" name="photo"class="form-control" />
              </div>

              <div class="form-group">
                 <input type="submit" value="Update" class="btn btn-success float-right">
              </div>
          
             
            </div>
			</form>
         
          </div>
         
        </div>
        
      </div>
     
       
    </section>
    <!-- /.content -->
  </div>

</div> 
 @endsection